
import java.util.Random;
import java.util.Arrays;
import java.util.Scanner;
public class MatrixOperations {

    public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
        
        // Define matrix size
        int rows, cols;
        System.out.println("Insert the matrix row number");
        rows = scanner.nextInt();
        System.out.println("Insert the matrix col number");
        cols = scanner.nextInt();
        
        System.out.println("Matrix generated by cols: \\n" + Arrays.deepToString(generateNewMatrixByCols(rows, cols)));// "
        System.out.println("Matrix generated by rows: \\n" + Arrays.deepToString(generateNewMatrixByRows(rows, cols)));// "
     
        int[][] matrixByRows = generateNewMatrixByRows(rows, cols);
        System.out.println("");
        displayMatrix(matrixByRows);
        System.out.println("");
        int[][] matrixByCols = generateNewMatrixByCols(rows, cols);
        displayMatrix(matrixByCols);
        
    }

    public static int[][] generateNewMatrixByRows(int rows, int cols) {
        int[][] newMatrix = new int[rows][cols];
        Random rand = new Random();
        int count = 0;
        // Fill matrix by rows:

        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                count++;
                newMatrix[i][j] = count;
            }
        }
        return newMatrix;

    }

    public static int[][] generateNewMatrixByCols(int rows, int cols) {
        int[][] newMatrix = new int[rows][cols];
        Random rand = new Random();
        int count = 0;
        // Fill matrix by cols:

        for (int j = 0; j < cols; j++) {
            for (int i = 0; i < rows; i++) {
                 count++;
                newMatrix[i][j] = count;
            }
        }
        return newMatrix;

    }

    public static void displayMatrix(int[][] matrix) {
        /*
        Another way of displaying the values:
        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[i].length; j++) {
                System.out.print(matrix[i][j] + " ");
            }
            System.out.println();
        }
        */

        for (int[] row : matrix) {
            for (int element : row) {
                System.out.print(element + " ");
            }
            System.out.println();
        }

    }

}
